[package]
name = "bajsucks/paralib"
description = "Simplest parallelization library."
license = "MIT"
authors = ["baj"]
repository = "https://github.com/bajsucks/paralib"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
signalplus = "alexanderlindholt/signalplus@*"